// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyLsCOxL6ysgp1E3JTdn8iRBfBNk5oqaw',
    appId: '1:760592855156:web:fc2990209fc50b1f176121',
    messagingSenderId: '760592855156',
    projectId: 'fcai-ass1',
    authDomain: 'fcai-ass1.firebaseapp.com',
    storageBucket: 'fcai-ass1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuylqbH-asFR-6U4UdXe1e4b7Jf9hQHj0',
    appId: '1:760592855156:android:c6731a571e8da199176121',
    messagingSenderId: '760592855156',
    projectId: 'fcai-ass1',
    storageBucket: 'fcai-ass1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg-EaIwtXI-XafZubWMoGJ02IAwZMuQ6M',
    appId: '1:760592855156:ios:15cbbeb902ec9b3e176121',
    messagingSenderId: '760592855156',
    projectId: 'fcai-ass1',
    storageBucket: 'fcai-ass1.firebasestorage.app',
    iosBundleId: 'com.example.ass1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg-EaIwtXI-XafZubWMoGJ02IAwZMuQ6M',
    appId: '1:760592855156:ios:15cbbeb902ec9b3e176121',
    messagingSenderId: '760592855156',
    projectId: 'fcai-ass1',
    storageBucket: 'fcai-ass1.firebasestorage.app',
    iosBundleId: 'com.example.ass1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyLsCOxL6ysgp1E3JTdn8iRBfBNk5oqaw',
    appId: '1:760592855156:web:a7b08b7dfc787ba7176121',
    messagingSenderId: '760592855156',
    projectId: 'fcai-ass1',
    authDomain: 'fcai-ass1.firebaseapp.com',
    storageBucket: 'fcai-ass1.firebasestorage.app',
  );
}
